FROM eclipse-temurin:21-jre

ENV PASSPORT_HOME /usr/local/passport
RUN mkdir -p "$PASSPORT_HOME"
WORKDIR $PASSPORT_HOME

COPY ./target/passport-2.3.1.jar .
COPY ./docker/deployment/docker-entrypoint.sh .
RUN chmod +x docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
